"""initial_schema

Creates the full schema from the SQLAlchemy models. Building the initial
revision straight from ``Base.metadata`` (rather than a hand-maintained
autogenerate dump) keeps this migration guaranteed-in-sync with
``app/db/sis_models.py`` for the very first deploy.

Later schema changes should be normal autogenerated revisions layered on top
of this one (``alembic revision --autogenerate -m "..."``).

Revision ID: 4e6ea02da8ab
Revises:
Create Date: 2026-06-04 23:05:20.643021
"""
from typing import Sequence, Union

from alembic import op

from app.db.base import Base
from app.db.models import import_models

# revision identifiers, used by Alembic.
revision: str = '4e6ea02da8ab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    import_models()  # register every mapped model on Base.metadata
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    import_models()
    Base.metadata.drop_all(bind=op.get_bind())
